#!/bin/csh -f
# local version, all maproom pages have relative paths.
# this must be run in the directory that has all the maproom subdirs, like /data/jdcorral/iri_html/ingrid/maproom
date --iso-8601=minutes
/bin/rm -rf ./newmaproomcache/*
 java -Xmx2048m -jar /data/jdcorral/SVN4/generatentriple/build/dist/generatentriples.jar -cache=newmaproomcache file://{$PWD}/maproomregistry.owl > newmaproomlog.`date --iso-8601=minutes`
# java -Xmx2048m -Dhttp.proxyHost=iridl2p.ldeo.columbia.edu -Dhttp.proxyPort=3128 -jar dist/generatentriples.jar -cache=newmaproomcache http://iri.columbia.edu/~jdcorral/ontologies/maproomregistry.owl > newmaproomlog.`date --iso-8601=minutes`

# local version, use trig file in newmaproomcache

date --iso-8601=minutes
/bin/rm -rf ./constructcache/*
java -Xmx2048m -jar /data/jdcorral/SVN4/generatentriple/build/dist/generatentriples.jar -cache=constructcache -loadfromtrig=newmaproomcache/owlimMaxRepository.trig -construct=/data/jdcorral/maproomtools/maproom_section_index.serql -constructoutput=./tabs.nt file://{$PWD}/maproomregistry.owl > constructlog.`date --iso-8601=minutes`

date --iso-8601=minutes
rapper -q -i ntriples -o rdfxml-abbrev tabs.nt > tabs.xml

# external version
date --iso-8601=minutes
/data/jdcorral/Sesame2/bin/sesame2_console.sh <<EOT
connect http://iridlc6.ldeo.columbia.edu:8380/openrdf-sesame.
open newmaproom-owl.
clear.
load newmaproomcache/owlimMaxRepository.nt.
EOT
date --iso-8601=minutes
