#!/bin/csh -f
# local version, all maproom pages have relative paths.
# this must be run in the directory that has all the maproom subdirs, like /data/jdcorral/iri_html/ingrid/maproom

echo "Gathering rdfa triples"

date --iso-8601=minutes
/bin/rm -rf ./newmaproomcache/*
 java -Xmx2048m -jar /data/jdcorral/SVN4/generatentriple/build/dist/generatentriples.jar -cache=newmaproomcache file://{$PWD}/maproomregistry.owl > newmaproomlog.`date --iso-8601=minutes`
# java -Xmx2048m -Dhttp.proxyHost=iridl2p.ldeo.columbia.edu -Dhttp.proxyPort=3128 -jar dist/generatentriples.jar -cache=newmaproomcache file://{$PWD}/maproomregistry.owl > newmaproomlog.`date --iso-8601=minutes`

# local version, use trig file in newmaproomcache

echo "Running CONSTRUCT query for tabs.xml"

date --iso-8601=minutes
/bin/rm -rf ./constructcache/*
java -Xmx2048m -jar /data/jdcorral/SVN4/generatentriple/build/dist/generatentriples.jar -cache=constructcache -loadfromtrig=newmaproomcache/owlimMaxRepository.trig -construct=/data/jdcorral/git_build/ingrid/maproomtools/maproom_section_index.serql -constructoutput=./tabs.nt file://{$PWD}/maproomregistry.owl > constructlog.`date --iso-8601=minutes`

date --iso-8601=minutes
#convert tabs.nt to tabs.xml
rapper -q -i ntriples -o rdfxml-abbrev tabs.nt > tabs.xml

date --iso-8601=minutes
